// Generated by https://quicktype.io

export interface AxiosWatchlistPopular {
    next: boolean;
    page: number;
    count: number;
    data: Datum[];
}

export interface Datum {
    _id: ID;
    count: number;
}

export interface ID {
    slug: string;
    title: string;
    id: string;
}
