// Generated by https://quicktype.io

export interface IGResult {
    hits: Hit[];
    nbHits: number;
    page: number;
    nbPages: number;
    hitsPerPage: number;
    exhaustiveNbHits: boolean;
    exhaustiveTypo: boolean;
    query: Query;
    params: string;
    processingTimeMS: number;
}

export interface Hit {
    lang: string;
    name: string;
    prod_id: string;
    seo_name: string;
    small_name: string;
    type: string;
    region: string;
    is_dlc: string;
    preorder: string;
    brand: string;
    is_draft: string;
    is_delivered: string;
    other_platforms_prod_id: null | string;
    similar_prod_id: string;
    promo: string;
    discount: number;
    sites: string[];
    sites_prices: SitesPrices;
    platforms: string[];
    price: number;
    retail: string;
    category: string[];
    search_tags: string[];
    avail_date: number;
    vpn_countries: null;
    exclude_from_search: string;
    langs: string[];
    manual_search_tags: null;
    developer_id: string;
    publisher_id: string;
    is_free_to_play: string;
    developer_name: string;
    publisher_name: string;
    platform: string;
    reviews_avg: number;
    cat_ids: Array<number | string>;
    lcat: string;
    objectID: string;
    _highlightResult: HighlightResult;
}

export interface HighlightResult {
    name: DeveloperName;
    small_name: DeveloperName;
    search_tags: DeveloperName[];
    developer_name: DeveloperName;
    publisher_name: DeveloperName;
}

export interface DeveloperName {
    value: string;
    matchLevel: MatchLevel;
    fullyHighlighted?: boolean;
    matchedWords: Query[];
}

export enum MatchLevel {
    Full = "full",
    None = "none",
}

export enum Query {
    Tun = "tun",
}

export interface SitesPrices {
    ig: number;
}
