// Generated by https://quicktype.io

export interface FanaticalResult {
    hits: Hit[];
    nbHits: number;
    page: number;
    nbPages: number;
    hitsPerPage: number;
    exhaustiveNbHits: boolean;
    exhaustiveTypo: boolean;
    query: string;
    queryAfterRemoval: string;
    params: string;
    processingTimeMS: number;
}

export interface Hit {
    product_id: string;
    sku: string;
    name: string;
    slug: string;
    type: string;
    display_type: string;
    cover: string;
    tiered: boolean;
    discount_percent: number;
    best_ever: boolean;
    flash_sale: boolean;
    price: { [key: string]: number };
    fullPrice: { [key: string]: number };
    operating_systems: string[];
    drm: string[];
    features: string[];
    collections: string[];
    video: string[];
    available_valid_from: number;
    available_valid_until: number;
    release_date: number;
    presale: boolean;
    hide_discount: boolean;
    hide_price: boolean;
    giveaway: boolean;
    ubisoft_ska: boolean;
    epic_ska: boolean;
    origin_ska: boolean;
    no_release_date: boolean;
    free_to_play: boolean;
    mystery: boolean;
    pay_what_you_want: boolean;
    game_total: number;
    dlc_total: number;
    bundle_covers: any[];
    screenshots: string[];
    video_clip_files: VideoClipFile[];
    video_clip_poster: number | string;
    age_ratings: AgeRatings;
    rating_score?: number;
    total_ratings?: number;
    total_recommended?: number;
    percent_recommended?: number;
    metacritic_score: number;
    opencritic_score: number | null;
    objectID: string;
}

export interface AgeRatings {
    ESRB: number;
    PEGI: number;
    USK: number;
    ACB: number;
}

export interface VideoClipFile {
    fileType: FileType;
    resolution: Resolution;
    path: string;
}

export enum FileType {
    Mp4 = "mp4",
    Webm = "webm",
}

export enum Resolution {
    The240P = "240p",
    The360P = "360p",
    The480P = "480p",
}
