// Generated by https://quicktype.io

export interface AxiosGithubReleases {
    url: string;
    assets_url: string;
    upload_url: string;
    html_url: string;
    id: number;
    author: Author;
    node_id: string;
    tag_name: string;
    target_commitish: string;
    name: string;
    draft: boolean;
    prerelease: boolean;
    created_at: string;
    published_at: string;
    assets: Asset[];
    tarball_url: string;
    zipball_url: string;
    body: string;
    reactions?: Reactions;
}

export interface Asset {
    url: string;
    id: number;
    node_id: string;
    name: string;
    label: null;
    uploader: Author;
    content_type: ContentType;
    state: State;
    size: number;
    download_count: number;
    created_at: string;
    updated_at: string;
    browser_download_url: string;
}

export enum ContentType {
    ApplicationJavascript = "application/javascript",
    TextJavascript = "text/javascript",
}

export enum State {
    Uploaded = "uploaded",
}

export interface Author {
    login: Login;
    id: number;
    node_id: NodeID;
    avatar_url: string;
    gravatar_id: string;
    url: string;
    html_url: string;
    followers_url: string;
    following_url: string;
    gists_url: GistsURL;
    starred_url: string;
    subscriptions_url: string;
    organizations_url: string;
    repos_url: string;
    events_url: EventsURL;
    received_events_url: string;
    type: Type;
    site_admin: boolean;
}

export enum EventsURL {
    HTTPSAPIGithubCOMUsersAcdliteEventsPrivacy = "https://api.github.com/users/acdlite/events{/privacy}",
    HTTPSAPIGithubCOMUsersBvaughnEventsPrivacy = "https://api.github.com/users/bvaughn/events{/privacy}",
    HTTPSAPIGithubCOMUsersGaearonEventsPrivacy = "https://api.github.com/users/gaearon/events{/privacy}",
    HTTPSAPIGithubCOMUsersLunaruanEventsPrivacy = "https://api.github.com/users/lunaruan/events{/privacy}",
    HTTPSAPIGithubCOMUsersThreepointoneEventsPrivacy = "https://api.github.com/users/threepointone/events{/privacy}",
}

export enum GistsURL {
    HTTPSAPIGithubCOMUsersAcdliteGistsGistID = "https://api.github.com/users/acdlite/gists{/gist_id}",
    HTTPSAPIGithubCOMUsersBvaughnGistsGistID = "https://api.github.com/users/bvaughn/gists{/gist_id}",
    HTTPSAPIGithubCOMUsersGaearonGistsGistID = "https://api.github.com/users/gaearon/gists{/gist_id}",
    HTTPSAPIGithubCOMUsersLunaruanGistsGistID = "https://api.github.com/users/lunaruan/gists{/gist_id}",
    HTTPSAPIGithubCOMUsersThreepointoneGistsGistID = "https://api.github.com/users/threepointone/gists{/gist_id}",
}

export enum Login {
    Acdlite = "acdlite",
    Bvaughn = "bvaughn",
    Gaearon = "gaearon",
    Lunaruan = "lunaruan",
    Threepointone = "threepointone",
}

export enum NodeID {
    MDQ6VXNlcjE4ODA4 = "MDQ6VXNlcjE4ODA4",
    MDQ6VXNlcjI3MzU1MTQ = "MDQ6VXNlcjI3MzU1MTQ=",
    MDQ6VXNlcjI5NTk3 = "MDQ6VXNlcjI5NTk3",
    MDQ6VXNlcjM2MjQwOTg = "MDQ6VXNlcjM2MjQwOTg=",
    MDQ6VXNlcjgxMDQzOA = "MDQ6VXNlcjgxMDQzOA==",
}

export enum Type {
    User = "User",
}

export interface Reactions {
    url: string;
    total_count: number;
    "+1": number;
    "-1": number;
    laugh: number;
    hooray: number;
    confused: number;
    heart: number;
    rocket: number;
    eyes: number;
}
