// Generated by https://quicktype.io

export interface HumbleResult {
    hits: Hit[];
    nbHits: number;
    page: number;
    nbPages: number;
    hitsPerPage: number;
    exhaustiveNbHits: boolean;
    exhaustiveTypo: boolean;
    query: string;
    params: string;
    processingTimeMS: number;
}

export interface Hit {
    current_sale: CurrentSale;
    cyoc_split: number;
    current_pricing: Pricing;
    has_dlc_cta: boolean;
    _tags: any[];
    platforms: string[];
    icon_dict: IconDict;
    exclusive_countries: string;
    developer: string[];
    genres: string[];
    price_gbp: number;
    wallet_reload: boolean;
    sort_date: number;
    full_pricing: Pricing;
    cta_badge: string;
    type: string;
    incompatible_features: any[];
    available: number;
    delivery_methods: string[];
    description: string;
    publisher: string[];
    machine_name: string;
    has_base_game: boolean;
    discount: number;
    link: string;
    storefront_icon: string;
    preorder: number;
    price_usd: number;
    rewards_split: number;
    localized_prices: { [key: string]: LocalizedPrice };
    disallowed_countries: string;
    payee: string[];
    is_live: boolean;
    release: number;
    human_name: string;
    start_dt: number;
    end_dt: number;
    price_eur: number;
    objectID: string;
    _highlightResult: HighlightResult;
}

export interface HighlightResult {
    platforms: CtaBadge[];
    developer: CtaBadge[];
    genres: CtaBadge[];
    cta_badge: CtaBadge;
    delivery_methods: CtaBadge[];
    description: CtaBadge;
    publisher: CtaBadge[];
    human_name: CtaBadge;
}

export interface CtaBadge {
    value: string;
    matchLevel: MatchLevel;
    matchedWords: string[];
    fullyHighlighted?: boolean;
}

export enum MatchLevel {
    Full = "full",
    None = "none",
}

export interface Pricing {
    RU: string[];
    EUROPE_EURO: string[];
    CA: string[];
    US: string[];
    NZ: string[];
    AU: string[];
    EUROPE_GBP: string[];
}

export interface CurrentSale {
    start: number;
    end: number;
}

export interface IconDict {
    steam: Steam;
}

export interface Steam {
    available: string[];
    unavailable: string[];
}

export interface LocalizedPrice {
    current_price: number;
    full_price: number;
}
