name: "Deploy to dokku"

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - name: Cloning repo
              uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
                  ref: master

            - name: Cache node_modules
              uses: actions/cache@v2.1.6
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 16

            - name: Install node_modules
              run: |
                  npm ci

            - name: Build the project
              run: |
                  rm .gitignore
                  mv .gitignore_prod .gitignore
                  npm run build:all
              env:
                  REDIS_URL: ${{ secrets.REDIS_URL }}
                  RAWG_KEY: ${{ secrets.RAWG_KEY }}

            - name: Save built files
              uses: EndBug/add-and-commit@v7.4.0
              with:
                  push: false
                  branch: master

            - name: Deploy to dokku
              uses: vitalyliber/dokku-github-action@v6.2
              env:
                  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  FORCE_DEPLOY: true
                  BRANCH: master
                  HOST: ${{ secrets.HOST }}
                  PROJECT: doto
